### ISSUE TITLE
Git tag is created on PR

### ISSUE THREAD

**Issue by kstruempf** [mathieudutour/github-tag-action#103]
Hi :) 
I started using this action in one of my projects and I really like it so far!
One issue came up thought:

My CI configuration looks like this:
```
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main','dev' ]

  get-version:
    name: 'Get Version'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

  build-stuff:
    name: 'Build and Push Docker Images'
    needs: [ get-version ]
    runs-on: ubuntu-latest        
    ... 
```
So the job runs on all pushes to main and all PRs into main and dev. The [README](https://github.com/mathieudutour/github-tag-action#filter-branches) states: 
> **release_branches** (optional) - Comma separated list of branches (JavaScript regular expression accepted) that will generate the release tags. Other branches and pull-requests generate versions postfixed with the commit hash and do not generate any repository tag.

So I would expect the action to output a value for `new_version`, but **not** create a new tag in the repository. However a new tag is being created on PRs.

Any help on this would be appreciated 😀
