### ISSUE TITLE
Produce additional major only tag

### ISSUE THREAD

**Issue by gajus** [mathieudutour/github-tag-action#109]
I need to publish two tags: vX.Y.Z and vX.

This is because GitHub actions do not support version ranges:

https://stackoverflow.com/questions/69399814/how-to-express-a-version-range-for-github-action-dependency

Is there a way to do it?

**Comment by mathieudutour** [comment]
no, especially because I think you will have to first delete the `vX` tag before being able to push it again

**Comment by gajus** [comment]
In case anyone else has such use case, this is how we did it:

```yml
      - uses: paulhatch/semantic-version@v4.0.2
        id: semantic_version
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}"
          change_path: "actions"
          short_tags: false
          bump_each_commit: false
      - name: Tag Release (vX.Y.Z)
        run: |
          git tag ${{ steps.semantic_version.outputs.version_tag }}
          git push origin ${{ steps.semantic_version.outputs.version_tag }}
      - name: Tag Release (vX)
        run: |
          git tag -d v${{ steps.semantic_version.outputs.major }} 2> /dev/null || echo 'local ref does not exist'
          git push origin :v${{ steps.semantic_version.outputs.major }} 2> /dev/null || echo 'remote ref does not exist'
          git tag v${{ steps.semantic_version.outputs.major }}
          git push origin v${{ steps.semantic_version.outputs.major }}
```
