### ISSUE TITLE
How do I make new_tag available locally?

### ISSUE THREAD

**Issue by pdehlke** [mathieudutour/github-tag-action#113]
Given this workflow:

```yaml
name: release
on:
  push:
    branches:
      main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - run: git tag -l
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_annotated_tag: true

    - run: git tag -l
  ```
  
Both invocations of `git tag -l` show the same list of tags. Downstream steps like `ncipollo/release-action` are aware of the tag that this action creates, but I have a step in a java project that makes decisions based on tags present locally, and it's failing to find `new_tag`.

Is this expected behavior? I am wildly confused as to how this action applies its new tag :(
