### ISSUE TITLE
Failing to push refs after tag is created

### ISSUE THREAD

**Issue by tomerleib** [mathieudutour/github-tag-action#118]
Hi,
I'm creating a workflow that creates a new tag, generates release notes, and pushes it to the main branch. The tagging job works as expected, but when I'm trying to push the code to the branch after the tag, I'm getting:  
`error: src refspec refs/heads/main matches more than one`

Here's the action.yaml file: 

```yaml
name: CI
on:
  push:
    branches:
      - main
      
permissions:
  contents: write
jobs:
  release:
    runs-on: [ self-hosted ]
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        id: tag_version
        uses: mathieudutour/tag-action@v6.0
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          default_bump: minor
                    
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          output: CHANGELOG.md
          headerLabel: "# 📑 Changelog"
          breakingLabel: '### 💥 Breaking'
          enhancementLabel: '### 🚀 Enhancements'
          bugsLabel: '### 🐛 Bug fixes'
          stripGeneratorNotice: true
          issues: false
          issuesWoLabels: false
          pullRequests: true
          prWoLabels: true
          author: true
          verbose: true
          sinceTag: v2.25.0
      - name: Commit CHANGELOG Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git add CHANGELOG.md
          git commit -m 'Update Changelog.'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}          
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Any idea why I cannot push new changes after the tag is created or how it should be done to work properly?
