### ISSUE TITLE
"Reference update failed" after pushing tag

### ISSUE THREAD

**Issue by jun0tpyrc** [mathieudutour/github-tag-action#121]
Tried using this action in multiple repos, worked for a while, then seem broken for "github release creations"

```
previous version was 0.1.0.

Analyzing commit: hotfix: Try fix githubactions release
The commit should not trigger a release
Analysis of 1 commits complete: no release

New version is 0.1.1.

New tag after applying prefix is release-20220404-v0.1.1.

Changelog is ### [0.1.1](https://github.com/XXXX/YYYY/compare/release-20220404-v0.1.0...release-20220404-v0.1.1) (2022-04-04)

.

```

Error: Reference update failed

**Comment by jun0tpyrc** [comment]
seem related to customization of `tag_prefix` , with that somtimes not working as intended 
```
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "release-${{ steps.time.outputs.time }}-v"
          create_annotated_tag: true
```
