### ISSUE TITLE
'append_to_pre_release_tag' returns the branch name when provided an empty string

### ISSUE THREAD

**Issue by victorhearnyeates** [mathieudutour/github-tag-action#122]
I want to create a new tag, but have no suffix added by the action. However the use of the ternary operator in the `action.ts` code means that it interepts this empty string as not providing a value and instead uses the default of the branch name.

https://github.com/mathieudutour/github-tag-action/blob/master/src/action.ts#L65

Basically, we need some way to be able to provide an empty string if we want nothing appended

**Comment by diogomonte** [comment]
I am looking for the same solution.

**Comment by epignatelli** [comment]
Duplicate of #163 

And I also have the same issue.

**Comment by mikejflex** [comment]
You could set all branches to be release branches so it generates a tag like main by default:
```
      - name: Push patch tag
        id: push_patch_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          # Ensure this branch is considered a release and it gets a normal tag
          release_branches: .*
```
