### ISSUE TITLE
No commits analysed but `new_tag` is bumped

### ISSUE THREAD

**Issue by Nouxx** [mathieudutour/github-tag-action#141]
Hi 👋🏻 

From the documentation (README) I understood that the `new_tag` output should be undefined if no new commits from the last tag were fetched.

> new_tag - The value of the newly calculated tag. Note that if there hasn't been any new commit, this will be undefined.

However, I was playing around with my workflow and ran it without any new commits, which seemed to be properly spotted by this action, but it bumped it anyway.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/30227758/183479048-9b5ebdac-933e-4aef-b7bb-177aaea5fcb6.png">
(I hide the information from my organization repo, hope it won't bother)

My develop branch is always ahead of my master (I'm using `rebase` instead of `merge`)

```
git log --pretty=oneline
xxx (HEAD -> develop, tag: 4.2.14, origin/master, origin/develop, origin/HEAD, master) chore(release): bump version to 4.2.14
xxx (tag: 4.2.13) chore(release): bump version to 4.2.13
xxx refactor: add a name for the bump-version job
xxx (tag: 4.2.12) chore(release): bump version to 4.2.12
```

Here's how I implemented the action:

```
env:
  production_branch: master
  development_branch: develop

jobs:
  generate-tag:
    name: Tag & Changelog Generation
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
      changelog: ${{ steps.tag.outputs.changelog }}
    steps:
      - name: "Checkout ${{ env.development_branch}}"
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          ref: ${{ env.development_branch}}

      - name: "Generate the tag (without pushing it)"
        id: tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          tag_prefix: ""
          release_branches: ${{ env.development_branch}}
```

Am I doing something wrong?
Thanks 🙏🏻
