### ISSUE TITLE
How to fix `Parameter token or opts.auth is required`

### ISSUE THREAD

**Issue by pickaxe828** [mathieudutour/github-tag-action#166]
## **Expected:**
No error

## **What's actually happening:**
[The original action](https://github.com/pickaxe828/Tally/actions/runs/4084709165/jobs/7041728849#step:3:11)
Part of the associated `.yml`:
```yml
- name: Bump version and push tag
  id: tag_version
  uses: mathieudutour/github-tag-action@v6.1
  with:
    github_token: ${{ inputs.github_token }}
```
Output:
```yml
Run mathieudutour/github-tag-action@v6.1
    default_bump: patch
    default_prerelease_bump: prerelease
    tag_prefix: v
    release_branches: master,main
    create_annotated_tag: false
    fetch_all_tags: false
    dry_run: false
Error: Parameter token or opts.auth is required
```
And stopped running.

## 
So what is token actually? I've tried adding the GitHub token to it
```yml
uses: mathieudutour/github-tag-action@v6.1
with:
  github_token: ${{ inputs.github_token }}
```

**Comment by yp28** [comment]
I am hitting this issue as well, using a personal access token. It previously worked with the exact same configuration.  My code is as follows:
```yaml
name: on-push-main
on:
  push:
    branches:
      - main

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.PAT }}
          fetch_all_tags: true
          release_branches: main
```
Nothing relevant changed, and the access token is not expired.
