### ISSUE TITLE
[HELP] [QUESTION] Pull request not generate changelog

### ISSUE THREAD

**Issue by tyki6** [mathieudutour/github-tag-action#170]
hello,
First thank you for your amazing work!
I got a question, currently when i merge a pull request with lot's of commit tag-action not generate full change-log from commit message.It's possible to do it with your actions?

# Example

i created a branch, committed 6 times
```
fix: remove white page
fix: use router instead of window.location
feat: add electron logging
fix: sanitize payload to avoid xss 
style: lint 
docs: update readme
```
i created a pull request with the name:
`fix(desktop): auto update (#134)`

i merged my pull request with this commit message(default GitHub commit message when you merge a pr):
```
fix(desktop): auto update (#134)
* fix: remove white page
* fix: use router instead of window.location
* feat: add electron logging
* fix: sanitize payload to avoid xss 
* style: lint 
* docs: update readme
```
change log output:

> Bug Fixes
> desktop: autoupdate (#137) (20086ca)
# Actual Behavior 
1. i create a branch named test
2. i commited multiple time with convential commit 
3. on GitHub when merge my pr with default commit message (pr name + all commit  message)
4. only first commit message working

# Wanted behavior
1. i create a branch named test
2. i committed multiple time with conventional commit 
3. on GitHub when merge my pr with default commit message (pr name + all commit  message)
4. i want to have a full changelog generated from pr commit message

**Comment by garinichsan** [comment]
any update? 
I encounter the same problem

**Comment by azagniotov** [comment]
@garinichsan @tyki6 

You need to set variables under the ` ncipollo/release-action`, see its docs: https://github.com/ncipollo/release-action?tab=readme-ov-file#release-action 

e.g.:

```
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v${{ steps.semantic_version.outputs.version_tag }}
          name: v${{ steps.semantic_version.outputs.version_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          makeLatest: true
          generateReleaseNotes: true
          skipIfReleaseExists: true
```
