### ISSUE TITLE
Bug: default_bump not respected + unwanted text added to tag

### ISSUE THREAD

**Issue by mariusgrueter** [mathieudutour/github-tag-action#174]
This action does not seem to work correctly.

```yaml
      - id: tag_version
        name: Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: "major" # also tried, major, minor
          tag_prefix: ""
```

Using this in a normal action with the latest tag available in my repo = `1.54.0` results in creating
a `new_tag` by this action:

`1.54.1-workflow.0`

which is not correct, as the expected result should be `2.0.0`
1. Major version is not incremented, the option is not respected
2. a Post text is applied: `-workflow.0``

EDIT:
v5.5 does it correctly, though it also attaches the anoying `-workflow.0` at the end of the tag
