### ISSUE TITLE
Suggestion - Use github.token

### ISSUE THREAD

**Issue by PieterjanDeClippel** [mathieudutour/github-tag-action#179]
Readme says:

Usage
-------
```
name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
```

Normally you should be able to replace `${{ secrets.GITHUB_TOKEN }}` with just `${{ github.token }}` like [here](https://github.com/MintPlayer/mintplayer-ng-bootstrap/blob/master/.github/workflows/publish-master.yml#L78) or [here](https://github.com/MintPlayer/MintPlayer.AspNetCore.SpaServices.Routing/blob/master/.github/workflows/publish-release.yml#L47)
