### ISSUE TITLE
Major bump create bump patch instead

### ISSUE THREAD

**Issue by Jerome1337** [mathieudutour/github-tag-action#194]
We use the action to bump major version.

Here is the configuration inside the workflow

```yaml
- name: Create New Tag
  id: tag
  uses: mathieudutour/github-tag-action@v6.1
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    default_bump: "major"
```

BUT the actions created a patch tag instead

```sh
Run mathieudutour/github-tag-action@v6.1
Previous tag was v213.0.0, previous version was 213.0.0.

# COMMITS ANALYSIS

Analysis of [37](https://github.com/XXXXX) commits complete: patch release
New version is 213.0.1.
New tag after applying prefix is v213.0.1.
```

Everything was working before 🤔
