### ISSUE TITLE
It produced tons of tags "v0.0.1-refs-tags-v0-0-1-refs-tags-v0-0-1-refs-tags-v0-0-1-refs-tags-v0-0-1-refs-tags-v0-0-1-refs-tags-v0-0-1-refs-tags-v0-0-1-refs-tags-v0-0-1-refs-tags-v0-0-1-refs-tags-v0-0-1-refs-tags-v0-0-1-fix-apicalls2-0-0-0-0-0-0-0-0-0-0-0.0"

### ISSUE THREAD

**Issue by opendeluxe** [mathieudutour/github-tag-action#213]
<img width="1232" alt="Screenshot 2024-05-10 at 12 28 35" src="https://github.com/mathieudutour/github-tag-action/assets/132100527/f6a140df-3e87-4819-9a35-74e044740fa5">

Github Action:
<img width="1507" alt="Screenshot 2024-05-10 at 12 22 10" src="https://github.com/mathieudutour/github-tag-action/assets/132100527/f4b4679c-bc65-482d-97f3-b949eeaf7c14">

I put the example from the README in a workflow and the result was tons of tags, one longer than the previous one, concatenating all these tag-names all together with every iteration:

```
name: Bump version
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

```
