### ISSUE TITLE
Field `pre_release_branches` isn't applying the tag as pre-release

### ISSUE THREAD

**Issue by luiz-otavio** [mathieudutour/github-tag-action#214]
Seems like even specifying the branches for pre-release tags in the field `pre_release_branches` the tag itself doesn't apply as pre-release.

Config:
```yml
      - name: Bump Version and Push Tag
        id: bump_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          release_branches: main
          pre_release_branches: develop
          fetch_all_tags: true
          default_bump: minor
          default_prerelease_bump: preminor
          tag_prefix: v
          append_to_pre_release_tag: "rc"
```

![image](https://github.com/mathieudutour/github-tag-action/assets/65752397/fc022c34-4b4f-4349-8a2a-c8d38974f022)
