### ISSUE TITLE
Shouldn't this action trigger "release" event ?

### ISSUE THREAD

**Issue by AleksIvanovSinglet** [mathieudutour/github-tag-action#44]
I am testing a separate CD job and have added to it a condition to execute only when on push to master, the "release" event is also triggered.

```
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    ...
  cd:
    if: github.event_name == 'push' && github.event_name == 'release'
```

As far as I understand, tag generators have the role to trigger the release event, so you can use it further down your workflow if you need to.

Does this one do that or I have misunderstood the process, in which case how should I go about it ?
