### ISSUE TITLE
Tags are never created

### ISSUE THREAD

**Issue by cloewen8** [mathieudutour/github-tag-action#47]
My goal is to tag all commits that pass testing. I have a template that already includes the tests. So I added this action to add the tags.

The action runs, whoever it never adds a tag. I tried with lightweight and annotated tags and with the exact same example configuration with no luck. I ended up asking for help on Stackoverflow and they recommended I report it as a bug: https://stackoverflow.com/questions/65227046/github-tag-action-does-not-add-tag/65227304#65227304

Here is my previous `build.yml` that included github-tag-action:
```yaml
# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  pull_request:
    branches: ['*']
  push:
    branches: ['master']

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          1.8,  # Minimum supported by Minecraft
          11,   # Current Java LTS
          15    # Latest version
        ]
        # and run on both Linux and Windows
        os: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: bump version and push tag
        id: tag_version
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' && matrix.java == '11' }}
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '11' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
```

And here was the last run with that action:
```
Run mathieudutour/github-tag-action@v5.1
  with:
    github_token: ***
    create_annotated_tag: true
    default_bump: patch
    tag_prefix: v
    release_branches: master
    dry_run: false
```
