### ISSUE TITLE
It creates a tag, but it doesn't push the tag

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [mathieudutour/github-tag-action#57]
I have a workflow that should be executed after a tag is pushed. If I push a tag manually, it is executed, but if the tag is created with this action, it is not executed.

**Comment by renzit** [comment]
a little late, but I had to deal with the same,
The thing is you had to set a specific PAT [ personal acces token ] and not use the default that github provide bc that doesnt trigger actions.

**Comment by chrisjohnson00** [comment]
So, something like this will help!

```
      - name: 'Create Tag'
        id: 'create-tag'
        uses: 'mathieudutour/github-tag-action@v5.5'
        with:
          github_token: '${{ secrets.REPO_ONLY }}'
```

**Comment by Obsecurus** [comment]
You can also trigger on `create` and guard for tags and pulls

```
on:
  create:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
jobs:
  job1:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/pull') }}
```
