### ISSUE TITLE
Unable to bump major or minor version

### ISSUE THREAD

**Issue by stijnpiron** [mathieudutour/github-tag-action#7]
Hi,

How can I bump the major or minor version with your action?
The patch level is bumping as expected, but this is default behaviour, all attempts to bump major or minor versions are just resulting in a patch level bump...
I tried the examples from the readme (e.g.: `feat(deploy_scripts): update script`), but this does not work.

my script code is as follows:
```
# Generate build nummer on each push to every branch, this will be used to generate tags and releases when merged into master.
name: Update buildnumber

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag - new
        id: buildnumber
        uses: mathieudutour/github-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print new version number.
        env:
          version_number: ${{ steps.buildnumber.outputs.new_tag }}
        run: echo $version_number
```

Any idea what's going wrong here?
Thanks!
