### ISSUE TITLE
Bump RC version number on the right at pre_release_branches.

### ISSUE THREAD

**Issue by renzit** [mathieudutour/github-tag-action#76]
Hi everyone, 
I use composer, and I need to bump the RC version as default behavior on prerelease branches.

**Expected**
v1.1-RC1
v1.1-RC2

Actual Output:
v1.1-RC.0
v1.2-RC.0

Do we have a specific way to do that?
Could be responsibility of the dev to explicitly say what they want to create as a RC, but will be fine if default is RC${n}

**Implementation:**
- name: Tag Bump version and push tag
  id: tag_version
  uses: mathieudutour/github-tag-action@v5.4
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    pre_release_branches: staging
    append_to_pre_release_tag: RC
    
output 2 runs
v1.1-RC.0
v1.2-RC.0
    
  Any recommendations?

**Comment by chrisjohnson00** [comment]
I've a setup which does RC versioning for all branches except `main`, what I'm doing differently is using a dynamic `append_to_pre_release_tag` which appends the github run id.  However, mine also end in `.0` and that's not because of this action, it's from the `semver` dependency in use.  I'm not sure if it's a bug there or not, but does seem odd.   Mine end up as `v0.1.2-rc-716932932.0` format.  It works great for my use as the run id is always growing.

```
      - name: 'Get calculated next version based on commit history'
        id: 'calculated-next-version'
        uses: 'mathieudutour/github-tag-action@v5.4'
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          release_branches: 'main'
          default_bump: 'patch'
          dry_run: 'true'
          append_to_pre_release_tag: 'rc-${{ github.run_id }}'
          pre_release_branches: '^((main(?!$)).+|(?!main).+)$'
```
I use this in `dry_run` because I don't create a RC tag, it's used later in my workflow for the tag on the docker container I push up.

Take a look, maybe it'll inspire success!!

https://github.com/chrisjohnson00/plex-library-updater/blob/main/.github/workflows/ci.yml#L33-L59
