### ISSUE TITLE
Invalid semver tag generated for Dependabot PRs

### ISSUE THREAD

**Issue by jimrazmus** [mathieudutour/github-tag-action#81]
I have a build and test workflow that runs on pull requests. It contains the following step:

```
      - name: Output roughly what version on merge will look like
        id: versioner
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_release_rules: "MAJOR:major,MINOR:minor,PATCH:patch"
          dry_run: true
```

Dependabot is configured to update github actions and has submitted a PR to update the above step use version 5.5.0. The build and test workflow fails on the above step with this error message:

Error: 3.0.2-dependabot/github_actions/mathieudutour/github-tag-action-v5.5.0 is not a valid semver.

It is not clear to me why github-tag-action is deriving that long string instead of a semver.
