### ISSUE TITLE
tag push not triggering other workflow even with PAT

### ISSUE THREAD

**Issue by steven-murray** [mathieudutour/github-tag-action#87]
I have the following action for tagging:

```
name: Bump Version
on:
  push:
    branches:
      - master
jobs:
  bump-version-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        # Ensure full history is gotten.
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.BUMP_VERSION }}
          default_bump: false
```

where `BUMP_VERSION` is a personal access token. I then have another workflow that is supposed to run on every push to deploy. This used to work but for some reason, now it is not working anymore. The action for the deploy is not triggering at all, even though the tag action above runs successfully and a tag/release is created. The deploy action simply has `on: push` at the top, which I thought should be triggered?
