### ISSUE TITLE
Prerelease not incrementing

### ISSUE THREAD

**Issue by JonErickson** [mathieudutour/github-tag-action#88]
Hello, I have the following configuration in my workflow and when pushing to my prerelease branch, the patch number is incrementing rather than the prerelease number.

```
- name: Bump Application Version and Tag
  id: tag_version
  uses: mathieudutour/github-tag-action@v5.5
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    release_branches: master
    pre_release_branches: releases/*
    append_to_pre_release_tag: prerelease
```

Example: The previous tag was v1.0.3-prerelease.0. I pushed a new commit to the branch and the new tag was v1.0.4-prerelease.0, not v1.0.3-prerelease.1. Do I need to change the default_bump? Is there a setting for incrementing the prerelease number when nothing is specified? Thanks
