### ISSUE TITLE
Not read new commit after push step

### ISSUE THREAD

**Issue by adrian-ub** [mathieudutour/github-tag-action#97]
```yml
- uses: actions/checkout@v2
- name: Create commit
  run: |
    git add dist
    git add .
    git commit -m "feat(svg): update simple icons"
    git push
    echo "GITHUB_SHA=$(git rev-parse main)" >> $GITHUB_ENV

- name: Bump version and push tag
  id: tag_version
  uses: mathieudutour/github-tag-action@v5.6
  with:
    tag_prefix: ""
    release_branches: main
    github_token: ${{ secrets.GITHUB_TOKEN }}
- name: Create a GitHub release
  uses: ncipollo/release-action@v1
  with:
    tag: ${{ steps.tag_version.outputs.new_tag }}
    name: Release ${{ steps.tag_version.outputs.new_tag }}
    body: ${{ steps.tag_version.outputs.changelog }}
```

Calculate the new version with the previous commits
