### ISSUE TITLE
Add input to change directory

### ISSUE THREAD

**Issue by AlexDCraig** [mathieudutour/github-tag-action#99]
It would be helpful to cover the case where a user checks out the repo, but to a non-traditional location. For example, suppose:

````
    - name: Check Out
      uses: actions/checkout@v2
      with:
        path: .source
````

It would be nice to run the action like so:

````
    - name: Apply Tag of Commit Hash to Master
      uses: mathieudutour/github-tag-action@v5.6
      with:
        path: .source
````
